/**
 * PDSChain Canonical Event Taxonomy & Enumerations (Phase 13)
 * 
 * Defines standardized, versioned event categories, severity levels,
 * finality states, and event types across all blockchain layers.
 */

const EventCategory = {
  BLOCK: 'BLOCK',
  BLOCKCHAIN: 'BLOCKCHAIN',
  TRANSACTION: 'TRANSACTION',
  CONTRACT: 'CONTRACT',
  CONSENSUS: 'CONSENSUS',
  VALIDATOR: 'VALIDATOR',
  NETWORK: 'NETWORK',
  SYNC: 'SYNC',
  RECOVERY: 'RECOVERY',
  TLS: 'TLS',
  KEY_MANAGEMENT: 'KEY_MANAGEMENT',
  DEPLOYMENT: 'DEPLOYMENT',
  SECURITY: 'SECURITY',
  SYSTEM: 'SYSTEM',
  AUDIT: 'AUDIT'
};

const EventSeverity = {
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  NOTICE: 'NOTICE',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  CRITICAL: 'CRITICAL'
};

const FinalityStatus = {
  PENDING: 'PENDING',
  OBSERVED: 'OBSERVED',
  ACCEPTED: 'ACCEPTED',
  COMMITTED: 'COMMITTED',
  CERTIFIED: 'CERTIFIED',
  FINALIZED: 'FINALIZED',
  REJECTED: 'REJECTED',
  REVERTED: 'REVERTED'
};

const EventType = {
  // --- Block Lifecycle ---
  BLOCK_PROPOSED: 'BLOCK_PROPOSED',
  BLOCK_RECEIVED: 'BLOCK_RECEIVED',
  BLOCK_ACCEPTED: 'BLOCK_ACCEPTED',
  BLOCK_CERTIFIED: 'BLOCK_CERTIFIED',
  BLOCK_FINALIZED: 'BLOCK_FINALIZED',
  BLOCK_REJECTED: 'BLOCK_REJECTED',
  BLOCK_REVERTED: 'BLOCK_REVERTED',
  BLOCK_VALIDATION_FAILED: 'BLOCK_VALIDATION_FAILED',

  // --- Transaction Lifecycle ---
  TRANSACTION_RECEIVED: 'TRANSACTION_RECEIVED',
  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  TRANSACTION_ADMITTED: 'TRANSACTION_ADMITTED',
  TRANSACTION_INCLUDED: 'TRANSACTION_INCLUDED',
  TRANSACTION_EXECUTED: 'TRANSACTION_EXECUTED',
  TRANSACTION_REVERTED: 'TRANSACTION_REVERTED',
  TRANSACTION_REJECTED: 'TRANSACTION_REJECTED',
  TRANSACTION_EXPIRED: 'TRANSACTION_EXPIRED',
  TRANSACTION_RECEIPT_CREATED: 'TRANSACTION_RECEIPT_CREATED',
  RECEIPT_ROOT_VERIFIED: 'RECEIPT_ROOT_VERIFIED',
  STATE_ROOT_VERIFIED: 'STATE_ROOT_VERIFIED',
  MERKLE_ROOT_VERIFIED: 'MERKLE_ROOT_VERIFIED',

  // --- EVM Contract Events ---
  CONTRACT_EVENT_EMITTED: 'CONTRACT_EVENT_EMITTED',
  CONTRACT_CALL_EXECUTED: 'CONTRACT_CALL_EXECUTED',
  CONTRACT_CALL_FAILED: 'CONTRACT_CALL_FAILED',
  CONTRACT_DEPLOYED: 'CONTRACT_DEPLOYED',

  // --- Consensus State Machine ---
  ROUND_STARTED: 'ROUND_STARTED',
  PROPOSAL_BROADCAST: 'PROPOSAL_BROADCAST',
  PROPOSAL_RECEIVED: 'PROPOSAL_RECEIVED',
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  PROPOSAL_REJECTED: 'PROPOSAL_REJECTED',
  CONSENSUS_PROPOSAL_BROADCAST: 'CONSENSUS_PROPOSAL_BROADCAST',
  CONSENSUS_PROPOSAL_RECEIVED: 'CONSENSUS_PROPOSAL_RECEIVED',
  VOTE_CAST: 'VOTE_CAST',
  VOTE_RECORDED: 'VOTE_RECORDED',
  CONSENSUS_VOTE_CAST: 'CONSENSUS_VOTE_CAST',
  CONSENSUS_VOTE_RECEIVED: 'CONSENSUS_VOTE_RECEIVED',
  DUPLICATE_VOTE_DETECTED: 'DUPLICATE_VOTE_DETECTED',
  DOUBLE_VOTE_DETECTED: 'DOUBLE_VOTE_DETECTED',
  EQUIVOCATION_DETECTED: 'EQUIVOCATION_DETECTED',
  CERTIFICATE_CREATED: 'CERTIFICATE_CREATED',
  CERTIFICATE_VERIFIED: 'CERTIFICATE_VERIFIED',
  CERTIFICATE_REJECTED: 'CERTIFICATE_REJECTED',
  CONSENSUS_CERTIFICATE_FORMED: 'CONSENSUS_CERTIFICATE_FORMED',
  ROUND_TIMEOUT: 'ROUND_TIMEOUT',
  ROUND_CHANGE: 'ROUND_CHANGE',
  CONSENSUS_ROUND_CHANGED: 'CONSENSUS_ROUND_CHANGED',
  QUORUM_UNAVAILABLE: 'QUORUM_UNAVAILABLE',
  CONSENSUS_HALTED: 'CONSENSUS_HALTED',
  CONSENSUS_RESUMED: 'CONSENSUS_RESUMED',

  // --- Validator Node Lifecycle ---
  VALIDATOR_STARTING: 'VALIDATOR_STARTING',
  VALIDATOR_STARTED: 'VALIDATOR_STARTED',
  VALIDATOR_STOPPED: 'VALIDATOR_STOPPED',
  CONFIG_LOADED: 'CONFIG_LOADED',
  IDENTITY_LOADED: 'IDENTITY_LOADED',
  VALIDATOR_READY: 'VALIDATOR_READY',
  CONSENSUS_READY: 'CONSENSUS_READY',
  VALIDATOR_DEGRADED: 'VALIDATOR_DEGRADED',
  VALIDATOR_RECOVERY_STARTED: 'VALIDATOR_RECOVERY_STARTED',
  VALIDATOR_HALTED: 'VALIDATOR_HALTED',
  VALIDATOR_STATUS_CHANGED: 'VALIDATOR_STATUS_CHANGED',
  VALIDATOR_SHUTTING_DOWN: 'VALIDATOR_SHUTTING_DOWN',
  VALIDATOR_RESTARTED: 'VALIDATOR_RESTARTED',
  VALIDATOR_CRASHED: 'VALIDATOR_CRASHED',

  // --- P2P Network & Transport ---
  PEER_CONNECTION_ATTEMPTED: 'PEER_CONNECTION_ATTEMPTED',
  PEER_CONNECTED: 'PEER_CONNECTED',
  TLS_HANDSHAKE_STARTED: 'TLS_HANDSHAKE_STARTED',
  TLS_HANDSHAKE_COMPLETED: 'TLS_HANDSHAKE_COMPLETED',
  APPLICATION_AUTH_COMPLETED: 'APPLICATION_AUTH_COMPLETED',
  PEER_DISCONNECTED: 'PEER_DISCONNECTED',
  PEER_REJECTED: 'PEER_REJECTED',
  PEER_REVOKED: 'PEER_REVOKED',
  HEARTBEAT_SENT: 'HEARTBEAT_SENT',
  HEARTBEAT_MISSED: 'HEARTBEAT_MISSED',
  HEARTBEAT_RESTORED: 'HEARTBEAT_RESTORED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_REJECTED: 'MESSAGE_REJECTED',
  FRAMING_ERROR: 'FRAMING_ERROR',
  BACKPRESSURE_ACTIVATED: 'BACKPRESSURE_ACTIVATED',

  // --- Ledger Synchronization & Recovery ---
  SYNC_STARTED: 'SYNC_STARTED',
  PEER_SELECTED: 'PEER_SELECTED',
  COMMON_ANCESTOR_FOUND: 'COMMON_ANCESTOR_FOUND',
  SYNC_RANGE_REQUESTED: 'SYNC_RANGE_REQUESTED',
  SYNC_BATCH_RECEIVED: 'SYNC_BATCH_RECEIVED',
  SYNC_BATCH_VERIFIED: 'SYNC_BATCH_VERIFIED',
  SYNC_BATCH_COMMITTED: 'SYNC_BATCH_COMMITTED',
  SYNC_RESUMED: 'SYNC_RESUMED',
  SYNC_INTERRUPTED: 'SYNC_INTERRUPTED',
  SYNC_COMPLETED: 'SYNC_COMPLETED',
  SYNC_FAILED: 'SYNC_FAILED',
  DIVERGENCE_DETECTED: 'DIVERGENCE_DETECTED',
  CONFLICTING_HISTORY_DETECTED: 'CONFLICTING_HISTORY_DETECTED',

  RECOVERY_STARTED: 'RECOVERY_STARTED',
  CHECKPOINT_LOADED: 'CHECKPOINT_LOADED',
  CHECKPOINT_VERIFIED: 'CHECKPOINT_VERIFIED',
  CHECKPOINT_CORRUPTED: 'CHECKPOINT_CORRUPTED',
  JOURNAL_REPLAY_STARTED: 'JOURNAL_REPLAY_STARTED',
  JOURNAL_REPLAY_COMPLETED: 'JOURNAL_REPLAY_COMPLETED',
  JOURNAL_REPLAY_FAILED: 'JOURNAL_REPLAY_FAILED',
  DATABASE_MISMATCH_DETECTED: 'DATABASE_MISMATCH_DETECTED',
  EVM_STATE_MISMATCH_DETECTED: 'EVM_STATE_MISMATCH_DETECTED',
  RECOVERY_COMPLETED: 'RECOVERY_COMPLETED',
  RECOVERY_HALTED: 'RECOVERY_HALTED',
  CONSENSUS_REJOIN_PERMITTED: 'CONSENSUS_REJOIN_PERMITTED',
  CONSENSUS_REJOIN_BLOCKED: 'CONSENSUS_REJOIN_BLOCKED',

  // --- TLS & Key Management (Phase 12) ---
  CERTIFICATE_LOADED: 'CERTIFICATE_LOADED',
  CERTIFICATE_EXPIRY_WARNING: 'CERTIFICATE_EXPIRY_WARNING',
  CERTIFICATE_VALIDATION_FAILED: 'CERTIFICATE_VALIDATION_FAILED',
  TLS_HANDSHAKE_FAILED: 'TLS_HANDSHAKE_FAILED',
  TLS_HANDSHAKE_SUCCEEDED: 'TLS_HANDSHAKE_SUCCEEDED',
  TLS_CERTIFICATE_RELOADED: 'TLS_CERTIFICATE_RELOADED',
  PEER_CERTIFICATE_REJECTED: 'PEER_CERTIFICATE_REJECTED',
  CERTIFICATE_ROTATED: 'CERTIFICATE_ROTATED',
  KEY_STAGED: 'KEY_STAGED',
  KEY_ACTIVATED: 'KEY_ACTIVATED',
  KEY_ROTATED: 'KEY_ROTATED',
  CONSENSUS_KEY_STAGED: 'CONSENSUS_KEY_STAGED',
  CONSENSUS_KEY_ROTATED: 'CONSENSUS_KEY_ROTATED',
  KEY_LOAD_FAILED: 'KEY_LOAD_FAILED',
  KEY_MISMATCH_DETECTED: 'KEY_MISMATCH_DETECTED',
  PEER_AUTHORIZATION_UPDATED: 'PEER_AUTHORIZATION_UPDATED',
  PEER_REVOKED_CRL: 'PEER_REVOKED_CRL',
  CERTIFICATE_REVOKED_CRL: 'CERTIFICATE_REVOKED_CRL',
  PEER_SUSPENDED: 'PEER_SUSPENDED',
  PEER_UNSUSPENDED: 'PEER_UNSUSPENDED'
};

module.exports = {
  EventCategory,
  EVENT_CATEGORIES: EventCategory,
  EventSeverity,
  EVENT_SEVERITIES: EventSeverity,
  FinalityStatus,
  FINALITY_STATUS: FinalityStatus,
  EventType,
  EVENT_TYPES: EventType
};
