/**
 * PDSChain Network Subsystem Error Codes & Typed Errors
 */

const NetworkErrorCode = {
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  MALFORMED_ENVELOPE: 'MALFORMED_ENVELOPE',
  OVERSIZED_FRAME: 'OVERSIZED_FRAME',
  TRUNCATED_FRAME: 'TRUNCATED_FRAME',
  UNKNOWN_MESSAGE_TYPE: 'UNKNOWN_MESSAGE_TYPE',
  PROTOCOL_VERSION_MISMATCH: 'PROTOCOL_VERSION_MISMATCH',
  NETWORK_ID_MISMATCH: 'NETWORK_ID_MISMATCH',
  CHAIN_ID_MISMATCH: 'CHAIN_ID_MISMATCH',
  UNAUTHORIZED_PEER: 'UNAUTHORIZED_PEER',
  IDENTITY_MISMATCH: 'IDENTITY_MISMATCH',
  CHALLENGE_FAILED: 'CHALLENGE_FAILED',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  QUEUE_OVERFLOW: 'QUEUE_OVERFLOW',
  PEER_DISCONNECTED: 'PEER_DISCONNECTED',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  HANDSHAKE_TIMEOUT: 'HANDSHAKE_TIMEOUT',
  DECODE_ERROR: 'DECODE_ERROR',
  SYNC_ERROR: 'SYNC_ERROR',
  BLOCK_SYNC_FAILED: 'BLOCK_SYNC_FAILED',
  DIVERGENCE_DETECTED: 'DIVERGENCE_DETECTED',
  CHECKPOINT_MISMATCH: 'CHECKPOINT_MISMATCH',
  INVALID_EXECUTION_ROOT: 'INVALID_EXECUTION_ROOT',
  SYNC_TIMEOUT: 'SYNC_TIMEOUT',
  CORRUPTED_LEDGER: 'CORRUPTED_LEDGER',
  CONSENSUS_REJOIN_BLOCKED: 'CONSENSUS_REJOIN_BLOCKED',
  // Phase 12: TLS/mTLS & Key Management
  MISSING_IDENTITY: 'MISSING_IDENTITY',
  INVALID_PRIVATE_KEY: 'INVALID_PRIVATE_KEY',
  INVALID_CERTIFICATE: 'INVALID_CERTIFICATE',
  CERTIFICATE_MISMATCH: 'CERTIFICATE_MISMATCH',
  UNKNOWN_ISSUER: 'UNKNOWN_ISSUER',
  EXPIRED_CERTIFICATE: 'EXPIRED_CERTIFICATE',
  NOT_YET_VALID_CERTIFICATE: 'NOT_YET_VALID_CERTIFICATE',
  REVOKED_CERTIFICATE: 'REVOKED_CERTIFICATE',
  VALIDATOR_IDENTITY_MISMATCH: 'VALIDATOR_IDENTITY_MISMATCH',
  KEY_USAGE_VIOLATION: 'KEY_USAGE_VIOLATION',
  REVOKED_PEER: 'REVOKED_PEER'
};

class NetworkError extends Error {
  /**
   * @param {string} code - NetworkErrorCode enum value
   * @param {string} message - Descriptive error message
   * @param {object} [details] - Diagnostic payload
   */
  constructor(code, message, details = {}) {
    super(message);
    this.name = 'NetworkError';
    this.code = code;
    this.details = details;
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, NetworkError);
    }
  }

  toJSON() {
    return {
      name: this.name,
      code: this.code,
      message: this.message,
      details: this.details
    };
  }
}

module.exports = {
  NetworkErrorCode,
  NetworkError
};

